/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroNoSicafRouteImport } from './routes/cadastro-no-sicaf'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos.index'
import { Route as ConteudosSlugRouteImport } from './routes/conteudos.$slug'
import { Route as ApiPublicTriagemRouteImport } from './routes/api/public/triagem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroNoSicafRoute = CadastroNoSicafRouteImport.update({
  id: '/cadastro-no-sicaf',
  path: '/cadastro-no-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosSlugRoute = ConteudosSlugRouteImport.update({
  id: '/conteudos/$slug',
  path: '/conteudos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTriagemRoute = ApiPublicTriagemRouteImport.update({
  id: '/api/public/triagem',
  path: '/api/public/triagem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro-no-sicaf': typeof CadastroNoSicafRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/api/public/triagem': typeof ApiPublicTriagemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro-no-sicaf': typeof CadastroNoSicafRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/conteudos': typeof ConteudosIndexRoute
  '/api/public/triagem': typeof ApiPublicTriagemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro-no-sicaf': typeof CadastroNoSicafRoute
  '/contato': typeof ContatoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/api/public/triagem': typeof ApiPublicTriagemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro-no-sicaf'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/conteudos/$slug'
    | '/conteudos/'
    | '/api/public/triagem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro-no-sicaf'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/conteudos/$slug'
    | '/conteudos'
    | '/api/public/triagem'
  id:
    | '__root__'
    | '/'
    | '/cadastro-no-sicaf'
    | '/contato'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/conteudos/$slug'
    | '/conteudos/'
    | '/api/public/triagem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroNoSicafRoute: typeof CadastroNoSicafRoute
  ContatoRoute: typeof ContatoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ConteudosSlugRoute: typeof ConteudosSlugRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
  ApiPublicTriagemRoute: typeof ApiPublicTriagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-no-sicaf': {
      id: '/cadastro-no-sicaf'
      path: '/cadastro-no-sicaf'
      fullPath: '/cadastro-no-sicaf'
      preLoaderRoute: typeof CadastroNoSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/$slug': {
      id: '/conteudos/$slug'
      path: '/conteudos/$slug'
      fullPath: '/conteudos/$slug'
      preLoaderRoute: typeof ConteudosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/triagem': {
      id: '/api/public/triagem'
      path: '/api/public/triagem'
      fullPath: '/api/public/triagem'
      preLoaderRoute: typeof ApiPublicTriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroNoSicafRoute: CadastroNoSicafRoute,
  ContatoRoute: ContatoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ConteudosSlugRoute: ConteudosSlugRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
  ApiPublicTriagemRoute: ApiPublicTriagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
